### ISSUE TITLE
app-photos-releae.apk does not install on my Pixel6a with GrapheneOS

### ISSUE THREAD

**Issue by rcorba** [lukaspieper/Gcam-Services-Provider#102]
app-photos-releae.apk (from Mar 6, 630kb) does not install (again) on my Pixel6a with GrapheneOS, writes: "App not installed as package conflicts with an existing package".

I already installed GCam services provider on my Pixel6a few days ago (right after installing GrapheneOS), together with Google Camera app and it was working. But then I had to install Google Play Services to be able to activate eSIM on my phone. So I uninstalled GCam services provider and installed necessary Google staff temporarily. I made eSim functional and uninstalled Google staff again. I also created a second account user and installed Google Play services there (to be able to use some necessary bank apps that needs it). On my primary user account there is no Google stuff anymore. When I am trying to install GCam services back again, app-photos-releae.apk is giving me the message "App not installed as package conflicts with an existing package".

It is probably not an issue of GCam service provider (but rather android?). I understood from internet, that there may be some residual files after first installation that prevent app to be installed (???). Is there something that I can do with it? I want my CG services and Google Camera back. Thank you for you advices. 

 - Device: Pixel 6a
 - OS/ROM: GrapheneOS current version on android 13
 - Google Camera version: not yet installed
 - Gcam-Services-Provider version: app-photos-releae.apk (from Mar 6, 630kb)

**Comment by lukaspieper** [comment]
>  I also created a second account user and installed Google Play services there (to be able to use some necessary bank apps that needs it). On my primary user account there is no Google stuff anymore. When I am trying to install GCam services back again, app-photos-releae.apk is giving me the message "App not installed as package conflicts with an existing package".

Hi, thanks for reaching out. This is a limitation by the Android system. I can't do anything about this. Please refer to this chapter in the [readme](https://github.com/lukaspieper/Gcam-Services-Provider#comparison-grapheneos-sandboxed-play-services).

If you have further questions, feel free to respond in this issue.
