### ISSUE TITLE
GSF no longer needed on GrapheneOS - README should be updated

### ISSUE THREAD

**Issue by matchboxbananasynergy** [lukaspieper/Gcam-Services-Provider#103]
Hey there! On its latest release, GrapheneOS makes it so apps that don't actually have a hard dependency on GSF or Play Services don't actually require installing GSF or Play Services accordingly.

Therefore, the documentation should be updated to reflect that. The way I see it right now, the only thing that Gcam Services Provider can possibly provide for people is the ability to open the in-app gallery without Google Photos, but Google Camera now works by default on a naked install, so it's *more or less* obsolete for GrapheneOS users.

Just thought I'd give a heads up, thank you!

Sources:

https://grapheneos.org/releases#2023040400

>add generic compatibility shim catching the exception from the Gservices provider being missing to enable apps like Google Camera and the Pixel eSIM firmware app (Google eSIM activation app is separate) to work without GSF installed since they don't have any actual hard dependency on either GSF or Play services

https://grapheneos.org/usage#google-camera

>Google Camera can take full advantage of the available cameras and image processing hardware as it can on the stock OS and does not require GSF or sandboxed Google Play on GrapheneOS.

**Comment by lukaspieper** [comment]
When I read the changelog I knew I had to update the README. Thanks for creating this issue as reminder. I just updated it.
