### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by achterstag** [lukaspieper/Gcam-Services-Provider#12]
Works fine on 4a, Android 11, gtcam 7.5

I have experienced inconsistent behavior with the Google-Photos shortcut in the camera app as described in the other ticket. It doesn't bother me, as I don't have Google-Photos installed and therefore don't expect the shortcut to work.

Thank you a lot!

**Comment by lukaspieper** [comment]
Many thanks for the positive feedback. The scope of this project is very limited as it is not a modification of the original app. 

There are modified Gcam versions that work with any Gallery app, but I personally stick with the unmodified versions.

Also I don't have the time to keep up with Google's update cycle at the moment. I'm still on version 7.5, no idea when I can get into newer versions.

Will close this issue as there is already a "feedback thread".
