### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [lukaspieper/Gcam-Services-Provider#122]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by lukaspieper** [comment]
Hi Izzy,

Thanks for getting in touch, and especially for taking such good care of your repository and users. I have just created a 1.5.1 release to fix this issue. It would be great if you could give me a quick confirmation from your end.

Thanks in advance.

**Comment by IzzySoft** [comment]
Thanks for the fast action – and for the kind words :star_struck: I'm really overwhelmed with the positive feedback I receive from the app authors to my reports. That's quite a motivation you all give me there, thanks a lot!

As for the feedback, how was the saying? "A picture speaks louder…"? So here comes a screenshot from the staging area, showing how it will look on "production" with the next sync around 7 pm UTC:

![image](https://github.com/lukaspieper/Gcam-Services-Provider/assets/6781438/c131c211-6a0b-4c9a-97ce-535ac2c64419)

The "WhatsNew" section comes from my local copy of the Fastlane structures, where I simply placed the matching `changelogs/7.txt` for both variants. As not all of it fit onto one screen, here's how it continues btw:

![image](https://github.com/lukaspieper/Gcam-Services-Provider/assets/6781438/c5957b9c-2a81-4e84-b5d2-640fecd7e510)

Your new cert is pinned here now, the old one will be removed in a month or so (together with the last "debug version"). Oh, and for the `DEPENDENCY_INFO_BLOCK`, easy to get rid of that if you want (as your apps are unlikely to go to PlayStore, there's no need of that block anyway):

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

So thanks a million again! I leave this issue open in case you want it as reminder for that BLOB. Feel free to close :smile:

**Comment by lukaspieper** [comment]
> Thanks for the fast action – and for the kind words 🤩 I'm really overwhelmed with the positive feedback I receive from the app authors to my reports. That's quite a motivation you all give me there, thanks a lot!

There were two reasons for the quick realisation, on the one hand I had already set up the signing for the previous release, but then messed up the GitHub release, so the signed APKs did not arrive in your repo, on the other hand I knew that I would have little time, as you can see from the delay of this answer. I'm delighted that you're getting such positive feedback from so many people, I think that's the least we can do for all the effort you're putting in. 

Thanks also for the hint regarding the `dependenciesInfo`. I've just committed the change, but I'm not planning on doing another release for this single change. It will have to wait for the next regular version.

> So thanks a million again!

I thank you for operating the repo and the extensive maintenance including the creation of dozens of tickets.

**Comment by IzzySoft** [comment]
> I had already set up the signing for the previous release

Ah, cool, so you were already on it and this just crossed :star_struck:

> I think that's the least we can do for all the effort you're putting in.

Thank you for seeing it this way! Yes, I invest a lot of time in getting my repo as secure and transparent as possible. I see this as a responsibility I have towards those using it – be it the developers entrusting their apps to me for distribution, or those using it as source for the apps they install (and the two are not mutually exclusives :wink:). Still, I was not prepared for this overwhelming positive feedback, and I still am (and will remain to be) very thankful for it. I don't (and can't) take it for granted.

> I'm not planning on doing another release for this single change. It will have to wait for the next regular version.

Totally fine with me! It's not "on focus" here yet, I've still enough to do with "the other open issues" (debug keys, flags, sensitive permissions, self-updaters). So currently I only mention it along when I reach out anyway. So these "signing block blobs" will come into focus later, maybe around summer. For some background you can take a look at my repo's info page under [SigningBlock checks](https://apt.izzysoft.de/fdroid/index/info#signingblock). I'll hopefully have a full blog article with more details available soon™, draft is ready but needs some polish.

> I thank you for operating the repo and the extensive maintenance including the creation of dozens of tickets.

Gladly, thanks! Just afraid you'd need to multiply the dozens by 10 or so :see_no_evil: Next to the issue linked above (477) there was also 475. And 477 is unlikely to be the last one…

Btw: If you want to participate in the next big thing, and your time permits (being the dev of your apps it should not take too much of your time I hope) – maybe you could provide the [build recipes](https://github.com/obfusk/rbtlog/tree/log/recipes) for your apps? :wink:
