### ISSUE TITLE
F-Droid update

### ISSUE THREAD

**Issue by SaeedDev94** [lukaspieper/Gcam-Services-Provider#142]
Thanks for this! Really useful 👍. 
Can you please keep F-Droid release up to date as well as GitHub releases?  
It would be great! Thanks ❤️

**Comment by lukaspieper** [comment]
Hi,

first of all thanks for the nice feedback. Glad you like it.

thanks to your issue I noticed that version 1.5.1 never made it to F-Droid. For now that version is available thru GitHub and Izzy's F-Droid Repo. What do you mean with *as well as GitHub releases*? What makes you think they are outdated?

@IzzySoft hope its okay to ask you for help this way. Version 1.5.1 never made it to F-Droid ([metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.lukaspieper.gcam.services.yml)). The metadata contains `AutoUpdateMode` and `UpdateCheckMode` and the latest release was taged. Looks right to me, doesn't it? I'm not that familiar with how F-Droid works. Would be great if you could give me a hint. Thanks.

**Comment by SaeedDev94** [comment]
> Hi,
> 
> first of all thanks for the nice feedback. Glad you like it.
> 
> thanks to your issue I noticed that version 1.5.1 never made it to F-Droid. For now that version is available thru GitHub and Izzy's F-Droid Repo. What do you mean with _as well as GitHub releases_? What makes you think they are outdated?

GitHub release is OK, my bad (sorry), I should said please update the F-Droid release when you release an update in GitHub, Thanks ❤️

**Comment by IzzySoft** [comment]
Easy answer Lukas: you forgot to [increase `versionCode`](https://github.com/lukaspieper/Gcam-Services-Provider/blob/v1.5.1/app/build.gradle#L17) – it's still at `6`, which F-Droid already has (v1.5), and thus ignores the tag.

**Comment by lukaspieper** [comment]
> Easy answer Lukas: you forgot to [increase `versionCode`](https://github.com/lukaspieper/Gcam-Services-Provider/blob/v1.5.1/app/build.gradle#L17) – it's still at `6`, which F-Droid already has (v1.5), and thus ignores the tag.

That's rather embarrassing. Sorry to have bothered you with such a simple issue. Will fix this asap.

**Comment by IzzySoft** [comment]
Eh, no worries. If we'd need to be embarrassed by such little things, we'd all run around with orange faces – oops :see_no_evil: (yeah, that guy has more than sufficient reason to). We all make our little mistakes :wink:

**Comment by lukaspieper** [comment]
> Eh, no worries. If we'd need to be embarrassed by such little things, we'd all run around with orange faces – oops 🙈 (yeah, that guy has more than sufficient reason to). We all make our little mistakes 😉

That's a great way of looking at things 👍🏻 

Version 1.5.2 is available on F-Droid since Thursday. I looks like it is not yet available on your repo @IzzySoft? Website shows version 1.5.1. Is there something I need to do? Thought you "harvest" the GitHub releases?

**Comment by IzzySoft** [comment]
> Thought you "harvest" the GitHub releases?

We do. Guess the IoD repo has meanwhile grown to a point where we hit API limits even at update checks already (despite of using an API key), and the updater needs to be, err, updated to catch those and then check the timeout accordingly to handle it.

![image](https://github.com/user-attachments/assets/825662a1-b952-45aa-9599-fd2909383446)

Manually triggered an update for both, will show up with the next sync. Thanks for letting me know!
