### ISSUE TITLE
Is the F-Droid version your build?

### ISSUE THREAD

**Issue by beerisgood** [lukaspieper/Gcam-Services-Provider#2]
https://f-droid.org/packages/com.google.android.gms

**Comment by lukaspieper** [comment]
No, it's not.

**Comment by beerisgood** [comment]
@lukaspieper okay.

As the client show a different app as the F-Droid online site, here a screenshot:
![Screenshot_20200825-161222](https://user-images.githubusercontent.com/9625159/91185373-09d85980-e6ee-11ea-9321-9672862b534e.png)

**Comment by lukaspieper** [comment]
That's interesting. When you visit the F-Droid website, you also see "UnifiedNlp (no GAPPS) Location Provider Middleware", don't you? I'm using Aurora Droid as F-Droid client and it also shows UnifiedNlp.

Propably a bug because of the same package name.

**Comment by beerisgood** [comment]
> That's interesting. When you visit the F-Droid website, you also see "UnifiedNlp (no GAPPS) Location Provider Middleware", don't you? I'm using Aurora Droid as F-Droid client and it also shows UnifiedNlp.

Yes. I also use official F-Droid.
