### ISSUE TITLE
Photo Sphere Viewer does not work

### ISSUE THREAD

**Issue by TippyLion28** [lukaspieper/Gcam-Services-Provider#48]
**Describe the bug**
My APK is based on GCAM 6.2. 

Navigating to the "More" menu shows a number of options including time lapse and slow motion. One such option is called "Photo Sphere" which allows me to take a 360° x 360° panorama kind of image. 

This works fine, however these images need to be viewed using a special view mode. On a GSM-enabled device this special mode is activated when you attempt to view the panorama. 

On my device with no GSF and with your mod installed, this view mode doesn't work, and instead I'm presented with the below error. 

![Screenshot_20210831-210127_Camera_1](https://user-images.githubusercontent.com/25936204/131879708-5b681d0e-805f-4b4c-8902-3d4886d700fb.png)

**To Reproduce**
1. Open GCAM
2. Go to "More" 
3. Tap photo-sphere
4. Take a photo-sphere
5. Try to open it from the image preview screen

**Expected behavior**
Panorama viewer opens 

**Log**
N/A

**Screenshots**
![Screenshot_20210831-210127_Camera_1](https://user-images.githubusercontent.com/25936204/131879995-82d1b2b6-99f2-4561-94ce-992d17ee7dc1.png)

**Smartphone (please complete the following information, the more detailed, the better)**
 - Device: [Poco F1]
 - OS/ROM: [e.g. Android 11, LineageOS 18.1]
 - Google Camera version (original, modified): [san1ty's Poco F1 GCAM 9.6 (Based on GCAM 6.2)]
 - Gcam-Services-Provider version: [app info says 1.1]

**Additional context**
Happy to provide further information

**Comment by lukaspieper** [comment]
Thank you for providing the necessary information. With my GCam version 8.2 it only says "360°", but I think it' s the mode you mean.

The problem should go back to issue #11, if you install the Google Photos app, the button should work because it is hard wired to Google Photos. Of course, this is not optimal, as the proprietary app is not an option for many users of my app for self-explanatory reasons.

**Comment by TippyLion28** [comment]
Hmm. That would make sense. It's not a huge issue, definitely not worth me installing a Google app to fix :-)

**Comment by lukaspieper** [comment]
There are modded Gcam versions that can use the default picture viewer, but I do not know if that works for 360° or if that modification is available for your device.

Hope it's okay to close this issue as duplicate. Feel free to comment after closing or create a new issue if there is any new information.
