### ISSUE TITLE
App is not installed issue.

### ISSUE THREAD

**Issue by Etern4lSaiy4n** [lukaspieper/Gcam-Services-Provider#49]
So I downloaded the file and tried to install it (havent compiled it myself as I dont know how) and I keep getting the "App not installed" message. I tried to install all 3 releases, none worked.

**Comment by lukaspieper** [comment]
Hi,

the installation is sadly not that simple. You need to follow one of the guides from issue #6.

**Comment by Etern4lSaiy4n** [comment]
I see, is there a step by step guide u can link me to?

**Comment by Etern4lSaiy4n** [comment]
alternatively, is there a way to use microG to make gcam usable since i do have microG installed? i know this is a noob question but im kinda new to "de-googled" phones and i dont yet fully understand the ins and outs of microG.

**Comment by lukaspieper** [comment]
I haven't tried it, but I'm quite sure that you cannot install microG and my app at the same time because both would provide the same service. 

You may need to install microG with `--force-queryable` as described in issue #6. But I'm not using microG myself, just a thought.

**Comment by Etern4lSaiy4n** [comment]
are there any specific options in microG that i would need to enable in order for gcam to work?

**Comment by lukaspieper** [comment]
> You may need to install microG with --force-queryable as described in issue #6. But I'm not using microG myself, just a thought.

Sorry but other than that I cannot help you. You need to tell the operating system (Android itself) that it should make a service visible to all apps. That's what `--force-queryable` is doing during installation.
