### ISSUE TITLE
casting??

### ISSUE THREAD

**Issue by fNCZsp5AV5n8d5** [lukaspieper/Gcam-Services-Provider#5]
The gcam services is awesome. I'm wondering if you have any plans to tackle streaming??

**Comment by lukaspieper** [comment]
Hi,

you are referring to sharing the screen or some media to a Tv, aren't you? As far as I know it has nothing to do with Gcam, therefore I do not plan to do anything in this direction.

**Comment by fNCZsp5AV5n8d5** [comment]
Yes, casting to a TV. Thanks for replying.
