### ISSUE TITLE
Gallery button doesn't open from Video mode

### ISSUE THREAD

**Issue by 2Belette** [lukaspieper/Gcam-Services-Provider#58]
**Describe the bug**

**To Reproduce**
1. Go to GCam
2. Click on Video
3. Take in video
4. Click on the gallery icon (bottom right)

**Expected behavior**
Clicking on the gallery icon should bring me in gallery like in Camera mode.

**Log**
No crash

**Screenshots**
No applicable

**Smartphone (please complete the following information, the more detailed, the better)**
 - Device: OnePlus 9T Pro
 - OS/ROM: LineageOs 18.1 (based on Android 11)
 - Google Camera version (original, modified): GCam_6.1Beta.210709.0049build-8.1.101
 - Gcam-Services-Provider version: 1.3

**Additional context**
Nothing to add

**Comment by lukaspieper** [comment]
Hi,

I actually fixed the problem [a couple of  days ago](https://github.com/lukaspieper/Gcam-Services-Provider/commit/ba9c2be0c2459ab77e857c51f302c1bc82d30025), but haven't created a new release yet. You can get a version including video support [from GitHub Actions](https://github.com/lukaspieper/Gcam-Services-Provider/actions/runs/1359922494).

I will make a new release available in the next few days.

Thanks.

**Comment by 2Belette** [comment]
Wonderful many thanks I will wait for the new release

**Comment by lukaspieper** [comment]
New release is available.
