### ISSUE TITLE
Can't Install the APK

### ISSUE THREAD

**Issue by Salyut9** [lukaspieper/Gcam-Services-Provider#67]
**Describe the bug**
The installation fail with "App not installed as package conflicts with an existing package."

From F-Droid it say "Error installing Gcam Services Provider (Basic) : Failed to install due to an unknown error"

**Smartphone (please complete the following information, the more detailed, the better)**
 - Device: Pixel 6
 - OS/ROM: GrapheneOS 12
 - Google Camera version : 8.4.3
 - Gcam-Services-Provider version: latest

**Comment by lukaspieper** [comment]
Hi,

some more context, e.g. a log would have been helpful to answer precisely to your use case. 

Generally speaking (as it says in the README), you can't use this app if you are using microg or GrapheneOS Sandboxed Play Services. If that doesn't apply to you and you were using my app before F-Droid, please make sure you uninstalled the old app first.

**Comment by Salyut9** [comment]
Hi,
Sorry I'm not sure how to provide log.

This is a fresh install of GrapheneOS, I'm not using MicroG and SandBoxed Play Service is only installed in Work Profile (Gcam-Services-Provider install was in Main Profile)
[log.txt](https://github.com/lukaspieper/Gcam-Services-Provider/files/7740800/log.txt)

**Comment by lukaspieper** [comment]
> SandBoxed Play Service is only installed in Work Profile

That is why it does not work, profiles are not virtual machines. The apps behind IDs must also be the same across profiles.

The easiest way for you is to install GSF in the current profile. You don't need the rest of the Google Play apps for Gcam.

**Comment by Salyut9** [comment]
It works, sorry for the inconvenience!

**Comment by lukaspieper** [comment]
No problem, you' re welcome. Glad you're happy with the end result.
