### ISSUE TITLE
Out of scope but question

### ISSUE THREAD

**Issue by julianfairfax** [lukaspieper/Gcam-Services-Provider#85]
I know this out of scope of this app, but I am wondering if it is possible to create a similar app that would do nothing other than remove those "this app won't run without Google Play Services" messages in apps. Since they're pretty much useless, it'd be a sight to see!

**Comment by aznd** [comment]
Actually, I have a very similar question. I have an game, Eggs. inc, which gives you an pop up telling that you need google play services installed. But it doesnt let you just click the dialog away, it closes the app after that.
So im asking you @lukaspieper how did you find out what package gcam needed? Maybe the same thing could be done to this game and i could create some stub package too?

**Comment by lukaspieper** [comment]
Hi guys,

sorry for my late and short reply. I'm quite busy currently. Please have a look on older issues. I'm sure that there is a least one or two similar issues and somewhere I explained how I build this application (fake service). 

Please excuse that I cannot deeply look into this in the next couple of weeks.

**Comment by julianfairfax** [comment]
You seem to be referring to https://github.com/lukaspieper/Gcam-Services-Provider/issues/30#issuecomment-822550399. I will attempt to carry out such a procedure on the offending apps and see how far I get.
