### ISSUE TITLE
Fail to install with conflict

### ISSUE THREAD

**Issue by mizzunet** [lukaspieper/Gcam-Services-Provider#95]
**Describe the bug**
Fail to install

**To Reproduce**
1. Try to install on CalyxOS 4.3.0(Android 13)

**Expected behavior**
Install

**Screenshots**
![Screenshot_20221206-221215](https://user-images.githubusercontent.com/10193999/205971451-d246867e-fbdf-407e-abe7-7538666d7aba.png)
![Screenshot_20221206-221118](https://user-images.githubusercontent.com/10193999/205971461-599faf5a-f977-458b-ba35-52d9dee82870.png)

**Smartphone (please complete the following information, the more detailed, the better)**
 - Device: Pixel 4A
 - OS/ROM: CalyxOS Anderoid 13
 - Google Camera version (original, modified): 8.2 and 7.r
 - Gcam-Services-Provider version: 1.1

**Additional context**

**Comment by lukaspieper** [comment]
Hi,

thanks for providing all the details. As far as I know CalyxOS ships with microg that is incompatible with this app as explained in the readme file. Therefor no bug here, sorry.
